/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deploy Configs Long Syntax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getSource <em>Source</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getTarget <em>Target</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getUid <em>Uid</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getGid <em>Gid</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getMode <em>Mode</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax()
 * @model
 * @generated
 */
public interface DeployConfigsLongSyntax extends DeployConfigs
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Uid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uid</em>' attribute.
   * @see #setUid(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax_Uid()
   * @model
   * @generated
   */
  String getUid();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getUid <em>Uid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uid</em>' attribute.
   * @see #getUid()
   * @generated
   */
  void setUid(String value);

  /**
   * Returns the value of the '<em><b>Gid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gid</em>' attribute.
   * @see #setGid(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax_Gid()
   * @model
   * @generated
   */
  String getGid();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getGid <em>Gid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gid</em>' attribute.
   * @see #getGid()
   * @generated
   */
  void setGid(String value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' attribute.
   * @see #setMode(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeployConfigsLongSyntax_Mode()
   * @model
   * @generated
   */
  String getMode();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.DeployConfigsLongSyntax#getMode <em>Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' attribute.
   * @see #getMode()
   * @generated
   */
  void setMode(String value);

} // DeployConfigsLongSyntax
