/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deploy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getEndpoint_mode <em>Endpoint mode</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getLabels <em>Labels</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getMode <em>Mode</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getPlacement <em>Placement</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getReplicas <em>Replicas</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getResources <em>Resources</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getRestart_policy <em>Restart policy</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getRollback_config <em>Rollback config</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getUpdate_config <em>Update config</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy()
 * @model
 * @generated
 */
public interface Deploy extends EObject
{
  /**
   * Returns the value of the '<em><b>Endpoint mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endpoint mode</em>' attribute.
   * @see #setEndpoint_mode(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Endpoint_mode()
   * @model
   * @generated
   */
  String getEndpoint_mode();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getEndpoint_mode <em>Endpoint mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Endpoint mode</em>' attribute.
   * @see #getEndpoint_mode()
   * @generated
   */
  void setEndpoint_mode(String value);

  /**
   * Returns the value of the '<em><b>Labels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labels</em>' containment reference.
   * @see #setLabels(Mapping)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Labels()
   * @model containment="true"
   * @generated
   */
  Mapping getLabels();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getLabels <em>Labels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Labels</em>' containment reference.
   * @see #getLabels()
   * @generated
   */
  void setLabels(Mapping value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' attribute.
   * @see #setMode(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Mode()
   * @model
   * @generated
   */
  String getMode();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getMode <em>Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' attribute.
   * @see #getMode()
   * @generated
   */
  void setMode(String value);

  /**
   * Returns the value of the '<em><b>Placement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Placement</em>' containment reference.
   * @see #setPlacement(Placement)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Placement()
   * @model containment="true"
   * @generated
   */
  Placement getPlacement();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getPlacement <em>Placement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Placement</em>' containment reference.
   * @see #getPlacement()
   * @generated
   */
  void setPlacement(Placement value);

  /**
   * Returns the value of the '<em><b>Replicas</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Replicas</em>' attribute.
   * @see #setReplicas(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Replicas()
   * @model
   * @generated
   */
  String getReplicas();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getReplicas <em>Replicas</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Replicas</em>' attribute.
   * @see #getReplicas()
   * @generated
   */
  void setReplicas(String value);

  /**
   * Returns the value of the '<em><b>Resources</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resources</em>' attribute.
   * @see #setResources(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Resources()
   * @model
   * @generated
   */
  String getResources();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getResources <em>Resources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resources</em>' attribute.
   * @see #getResources()
   * @generated
   */
  void setResources(String value);

  /**
   * Returns the value of the '<em><b>Restart policy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restart policy</em>' containment reference.
   * @see #setRestart_policy(RestartPolicy)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Restart_policy()
   * @model containment="true"
   * @generated
   */
  RestartPolicy getRestart_policy();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getRestart_policy <em>Restart policy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Restart policy</em>' containment reference.
   * @see #getRestart_policy()
   * @generated
   */
  void setRestart_policy(RestartPolicy value);

  /**
   * Returns the value of the '<em><b>Rollback config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rollback config</em>' containment reference.
   * @see #setRollback_config(DeployConfigs)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Rollback_config()
   * @model containment="true"
   * @generated
   */
  DeployConfigs getRollback_config();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getRollback_config <em>Rollback config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rollback config</em>' containment reference.
   * @see #getRollback_config()
   * @generated
   */
  void setRollback_config(DeployConfigs value);

  /**
   * Returns the value of the '<em><b>Update config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update config</em>' containment reference.
   * @see #setUpdate_config(DeployConfigs)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getDeploy_Update_config()
   * @model containment="true"
   * @generated
   */
  DeployConfigs getUpdate_config();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Deploy#getUpdate_config <em>Update config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update config</em>' containment reference.
   * @see #getUpdate_config()
   * @generated
   */
  void setUpdate_config(DeployConfigs value);

} // Deploy
