/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Or Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getListOrMapping()
 * @model
 * @generated
 */
public interface ListOrMapping extends EObject
{
} // ListOrMapping
