/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port Long Syntax</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getTarget <em>Target</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getPublished <em>Published</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getProtocol <em>Protocol</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getMode <em>Mode</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getPortLongSyntax()
 * @model
 * @generated
 */
public interface PortLongSyntax extends Ports
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getPortLongSyntax_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Published</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Published</em>' attribute.
   * @see #setPublished(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getPortLongSyntax_Published()
   * @model
   * @generated
   */
  String getPublished();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getPublished <em>Published</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Published</em>' attribute.
   * @see #getPublished()
   * @generated
   */
  void setPublished(String value);

  /**
   * Returns the value of the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' attribute.
   * @see #setProtocol(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getPortLongSyntax_Protocol()
   * @model
   * @generated
   */
  String getProtocol();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getProtocol <em>Protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' attribute.
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(String value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' attribute.
   * @see #setMode(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getPortLongSyntax_Mode()
   * @model
   * @generated
   */
  String getMode();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.PortLongSyntax#getMode <em>Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' attribute.
   * @see #getMode()
   * @generated
   */
  void setMode(String value);

} // PortLongSyntax
