/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Restart Policy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getDelay <em>Delay</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getMax_attempts <em>Max attempts</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getWindow <em>Window</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getRestartPolicy()
 * @model
 * @generated
 */
public interface RestartPolicy extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getRestartPolicy_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Delay</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay</em>' attribute.
   * @see #setDelay(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getRestartPolicy_Delay()
   * @model
   * @generated
   */
  String getDelay();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getDelay <em>Delay</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delay</em>' attribute.
   * @see #getDelay()
   * @generated
   */
  void setDelay(String value);

  /**
   * Returns the value of the '<em><b>Max attempts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max attempts</em>' attribute.
   * @see #setMax_attempts(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getRestartPolicy_Max_attempts()
   * @model
   * @generated
   */
  String getMax_attempts();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getMax_attempts <em>Max attempts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max attempts</em>' attribute.
   * @see #getMax_attempts()
   * @generated
   */
  void setMax_attempts(String value);

  /**
   * Returns the value of the '<em><b>Window</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Window</em>' attribute.
   * @see #setWindow(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getRestartPolicy_Window()
   * @model
   * @generated
   */
  String getWindow();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.RestartPolicy#getWindow <em>Window</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Window</em>' attribute.
   * @see #getWindow()
   * @generated
   */
  void setWindow(String value);

} // RestartPolicy
