/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Secrets</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getName <em>Name</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getFile <em>File</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getExternal <em>External</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getCustomName <em>Custom Name</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getSecrets()
 * @model
 * @generated
 */
public interface Secrets extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getSecrets_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getSecrets_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' attribute.
   * @see #setExternal(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getSecrets_External()
   * @model
   * @generated
   */
  String getExternal();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getExternal <em>External</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External</em>' attribute.
   * @see #getExternal()
   * @generated
   */
  void setExternal(String value);

  /**
   * Returns the value of the '<em><b>Custom Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Name</em>' attribute.
   * @see #setCustomName(String)
   * @see org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage#getSecrets_CustomName()
   * @model
   * @generated
   */
  String getCustomName();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.compose.composeFile.Secrets#getCustomName <em>Custom Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Name</em>' attribute.
   * @see #getCustomName()
   * @generated
   */
  void setCustomName(String value);

} // Secrets
