/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ComposeFileAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/palladiosimulator/somox/docker/compose/parser/antlr/internal/InternalComposeFileParser.tokens");
	}
}
