/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.dockerFile.impl;

import org.eclipse.emf.ecore.EClass;

import org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage;
import org.palladiosimulator.somox.docker.dockerFile.Entrypoint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entrypoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntrypointImpl extends InstructionImpl implements Entrypoint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntrypointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DockerFilePackage.Literals.ENTRYPOINT;
  }

} //EntrypointImpl
