/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.dockerFile.impl;

import org.eclipse.emf.ecore.EClass;

import org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage;
import org.palladiosimulator.somox.docker.dockerFile.EnvWithSpace;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Env With Space</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EnvWithSpaceImpl extends EnvImpl implements EnvWithSpace
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnvWithSpaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DockerFilePackage.Literals.ENV_WITH_SPACE;
  }

} //EnvWithSpaceImpl
