/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.composeFile.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage;
import org.palladiosimulator.somox.docker.compose.composeFile.ListOrMapping;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>List Or Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ListOrMappingImpl extends MinimalEObjectImpl.Container implements ListOrMapping
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListOrMappingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComposeFilePackage.Literals.LIST_OR_MAPPING;
  }

} //ListOrMappingImpl
