/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ComposeFileUiModule extends AbstractComposeFileUiModule {

	public ComposeFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
