/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.ide;


/**
 * Use this class to register ide components.
 */
public class DockerFileIdeModule extends AbstractDockerFileIdeModule {
}
