/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DockerFileStandaloneSetup extends DockerFileStandaloneSetupGenerated {

	public static void doSetup() {
		new DockerFileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
