/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDockerFileScopeProvider extends DelegatingScopeProvider {
}
