/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.dockerFile.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.palladiosimulator.somox.docker.dockerFile.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage
 * @generated
 */
public class DockerFileSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static DockerFilePackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DockerFileSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = DockerFilePackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case DockerFilePackage.DOCKERFILE:
      {
        Dockerfile dockerfile = (Dockerfile)theEObject;
        T result = caseDockerfile(dockerfile);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.INSTRUCTION:
      {
        Instruction instruction = (Instruction)theEObject;
        T result = caseInstruction(instruction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.CMD:
      {
        Cmd cmd = (Cmd)theEObject;
        T result = caseCmd(cmd);
        if (result == null) result = caseEntrypoint(cmd);
        if (result == null) result = caseInstruction(cmd);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ADD_DESTINATION:
      {
        AddDestination addDestination = (AddDestination)theEObject;
        T result = caseAddDestination(addDestination);
        if (result == null) result = caseInstruction(addDestination);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ENTRYPOINT:
      {
        Entrypoint entrypoint = (Entrypoint)theEObject;
        T result = caseEntrypoint(entrypoint);
        if (result == null) result = caseInstruction(entrypoint);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.VOLUME:
      {
        Volume volume = (Volume)theEObject;
        T result = caseVolume(volume);
        if (result == null) result = caseInstruction(volume);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.USER:
      {
        User user = (User)theEObject;
        T result = caseUser(user);
        if (result == null) result = caseInstruction(user);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ONBUILD:
      {
        Onbuild onbuild = (Onbuild)theEObject;
        T result = caseOnbuild(onbuild);
        if (result == null) result = caseInstruction(onbuild);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.FROM:
      {
        From from = (From)theEObject;
        T result = caseFrom(from);
        if (result == null) result = caseInstruction(from);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.MAINTAINER:
      {
        Maintainer maintainer = (Maintainer)theEObject;
        T result = caseMaintainer(maintainer);
        if (result == null) result = caseInstruction(maintainer);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ENV:
      {
        Env env = (Env)theEObject;
        T result = caseEnv(env);
        if (result == null) result = caseInstruction(env);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.EXPOSE:
      {
        Expose expose = (Expose)theEObject;
        T result = caseExpose(expose);
        if (result == null) result = caseInstruction(expose);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.JSON_ARRAY:
      {
        JSON_ARRAY jsoN_ARRAY = (JSON_ARRAY)theEObject;
        T result = caseJSON_ARRAY(jsoN_ARRAY);
        if (result == null) result = caseCmd(jsoN_ARRAY);
        if (result == null) result = caseAddDestination(jsoN_ARRAY);
        if (result == null) result = caseVolume(jsoN_ARRAY);
        if (result == null) result = caseEntrypoint(jsoN_ARRAY);
        if (result == null) result = caseInstruction(jsoN_ARRAY);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ENV_WITH_SPACE:
      {
        EnvWithSpace envWithSpace = (EnvWithSpace)theEObject;
        T result = caseEnvWithSpace(envWithSpace);
        if (result == null) result = caseEnv(envWithSpace);
        if (result == null) result = caseInstruction(envWithSpace);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.ENV_WITH_EQUAL:
      {
        EnvWithEqual envWithEqual = (EnvWithEqual)theEObject;
        T result = caseEnvWithEqual(envWithEqual);
        if (result == null) result = caseEnv(envWithEqual);
        if (result == null) result = caseInstruction(envWithEqual);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.WORKDIR:
      {
        Workdir workdir = (Workdir)theEObject;
        T result = caseWorkdir(workdir);
        if (result == null) result = caseInstruction(workdir);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.RUN:
      {
        Run run = (Run)theEObject;
        T result = caseRun(run);
        if (result == null) result = caseInstruction(run);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.RUN_WITH_SHELL:
      {
        RunWithShell runWithShell = (RunWithShell)theEObject;
        T result = caseRunWithShell(runWithShell);
        if (result == null) result = caseRun(runWithShell);
        if (result == null) result = caseInstruction(runWithShell);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case DockerFilePackage.RUN_WITH_NO_SHELL:
      {
        RunWithNoShell runWithNoShell = (RunWithNoShell)theEObject;
        T result = caseRunWithNoShell(runWithNoShell);
        if (result == null) result = caseRun(runWithNoShell);
        if (result == null) result = caseInstruction(runWithNoShell);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dockerfile</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dockerfile</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDockerfile(Dockerfile object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Instruction</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInstruction(Instruction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cmd</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cmd</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCmd(Cmd object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Add Destination</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Add Destination</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAddDestination(AddDestination object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Entrypoint</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Entrypoint</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEntrypoint(Entrypoint object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Volume</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Volume</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseVolume(Volume object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>User</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>User</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUser(User object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Onbuild</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Onbuild</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOnbuild(Onbuild object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>From</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>From</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFrom(From object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Maintainer</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Maintainer</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaintainer(Maintainer object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Env</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Env</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnv(Env object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expose</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expose</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpose(Expose object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>JSON ARRAY</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>JSON ARRAY</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseJSON_ARRAY(JSON_ARRAY object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Env With Space</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Env With Space</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnvWithSpace(EnvWithSpace object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Env With Equal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Env With Equal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnvWithEqual(EnvWithEqual object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Workdir</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Workdir</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWorkdir(Workdir object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Run</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Run</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRun(Run object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Run With Shell</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Run With Shell</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRunWithShell(RunWithShell object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Run With No Shell</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Run With No Shell</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRunWithNoShell(RunWithNoShell object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //DockerFileSwitch
