/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.palladiosimulator.somox.docker.compose.ide.contentassist.antlr.internal.InternalComposeFileParser;
import org.palladiosimulator.somox.docker.compose.services.ComposeFileGrammarAccess;

public class ComposeFileParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ComposeFileGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ComposeFileGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getServiceAccess().getAlternatives_4(), "rule__Service__Alternatives_4");
			builder.put(grammarAccess.getBuildAccess().getAlternatives(), "rule__Build__Alternatives");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getAlternatives_1(), "rule__BuildLongSyntax__Alternatives_1");
			builder.put(grammarAccess.getDeployConfigsAccess().getAlternatives(), "rule__DeployConfigs__Alternatives");
			builder.put(grammarAccess.getCredentialSpecAccess().getAlternatives(), "rule__CredentialSpec__Alternatives");
			builder.put(grammarAccess.getDeployAccess().getAlternatives_2(), "rule__Deploy__Alternatives_2");
			builder.put(grammarAccess.getPlacementAccess().getAlternatives_2(), "rule__Placement__Alternatives_2");
			builder.put(grammarAccess.getRestartPolicyAccess().getAlternatives_2(), "rule__RestartPolicy__Alternatives_2");
			builder.put(grammarAccess.getConfigAccess().getAlternatives_2(), "rule__Config__Alternatives_2");
			builder.put(grammarAccess.getHealthcheckAccess().getAlternatives_2(), "rule__Healthcheck__Alternatives_2");
			builder.put(grammarAccess.getPortsAccess().getAlternatives(), "rule__Ports__Alternatives");
			builder.put(grammarAccess.getServiceSecretsAccess().getAlternatives(), "rule__ServiceSecrets__Alternatives");
			builder.put(grammarAccess.getUlimitsAccess().getAlternatives(), "rule__Ulimits__Alternatives");
			builder.put(grammarAccess.getServiceVolumesAccess().getAlternatives_2(), "rule__ServiceVolumes__Alternatives_2");
			builder.put(grammarAccess.getVolumesAccess().getAlternatives_4(), "rule__Volumes__Alternatives_4");
			builder.put(grammarAccess.getNetworksAccess().getAlternatives_4(), "rule__Networks__Alternatives_4");
			builder.put(grammarAccess.getConfigsAccess().getAlternatives_4(), "rule__Configs__Alternatives_4");
			builder.put(grammarAccess.getSecretsAccess().getAlternatives_4(), "rule__Secrets__Alternatives_4");
			builder.put(grammarAccess.getValueOrListAccess().getAlternatives(), "rule__ValueOrList__Alternatives");
			builder.put(grammarAccess.getListOrMappingAccess().getAlternatives(), "rule__ListOrMapping__Alternatives");
			builder.put(grammarAccess.getMappingAccess().getAlternatives_1(), "rule__Mapping__Alternatives_1");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup(), "rule__DockerCompose__Group__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_4(), "rule__DockerCompose__Group_4__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_5(), "rule__DockerCompose__Group_5__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_6(), "rule__DockerCompose__Group_6__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_7(), "rule__DockerCompose__Group_7__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_8(), "rule__DockerCompose__Group_8__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_0(), "rule__Service__Group_4_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_1(), "rule__Service__Group_4_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_2(), "rule__Service__Group_4_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_3(), "rule__Service__Group_4_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_4(), "rule__Service__Group_4_4__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_5(), "rule__Service__Group_4_5__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_6(), "rule__Service__Group_4_6__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_7(), "rule__Service__Group_4_7__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_8(), "rule__Service__Group_4_8__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_9(), "rule__Service__Group_4_9__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_10(), "rule__Service__Group_4_10__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_11(), "rule__Service__Group_4_11__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_12(), "rule__Service__Group_4_12__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_13(), "rule__Service__Group_4_13__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_14(), "rule__Service__Group_4_14__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_15(), "rule__Service__Group_4_15__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_16(), "rule__Service__Group_4_16__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_17(), "rule__Service__Group_4_17__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_18(), "rule__Service__Group_4_18__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_19(), "rule__Service__Group_4_19__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_20(), "rule__Service__Group_4_20__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_21(), "rule__Service__Group_4_21__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_22(), "rule__Service__Group_4_22__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_23(), "rule__Service__Group_4_23__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_24(), "rule__Service__Group_4_24__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_25(), "rule__Service__Group_4_25__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_26(), "rule__Service__Group_4_26__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_27(), "rule__Service__Group_4_27__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_28(), "rule__Service__Group_4_28__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_29(), "rule__Service__Group_4_29__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_30(), "rule__Service__Group_4_30__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_31(), "rule__Service__Group_4_31__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_32(), "rule__Service__Group_4_32__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_33(), "rule__Service__Group_4_33__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_34(), "rule__Service__Group_4_34__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_35(), "rule__Service__Group_4_35__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_36(), "rule__Service__Group_4_36__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_37(), "rule__Service__Group_4_37__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_38(), "rule__Service__Group_4_38__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_39(), "rule__Service__Group_4_39__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_40(), "rule__Service__Group_4_40__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_41(), "rule__Service__Group_4_41__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_42(), "rule__Service__Group_4_42__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_43(), "rule__Service__Group_4_43__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_44(), "rule__Service__Group_4_44__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_45(), "rule__Service__Group_4_45__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_46(), "rule__Service__Group_4_46__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_47(), "rule__Service__Group_4_47__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_48(), "rule__Service__Group_4_48__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_49(), "rule__Service__Group_4_49__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_4_50(), "rule__Service__Group_4_50__0");
			builder.put(grammarAccess.getBuildAccess().getGroup_0(), "rule__Build__Group_0__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup(), "rule__BuildLongSyntax__Group__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_0(), "rule__BuildLongSyntax__Group_1_0__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_1(), "rule__BuildLongSyntax__Group_1_1__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_2(), "rule__BuildLongSyntax__Group_1_2__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_3(), "rule__BuildLongSyntax__Group_1_3__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_4(), "rule__BuildLongSyntax__Group_1_4__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_5(), "rule__BuildLongSyntax__Group_1_5__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_6(), "rule__BuildLongSyntax__Group_1_6__0");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getGroup_1_7(), "rule__BuildLongSyntax__Group_1_7__0");
			builder.put(grammarAccess.getDeployConfigsAccess().getGroup_0(), "rule__DeployConfigs__Group_0__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup(), "rule__DeployConfigsLongSyntax__Group__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup_1(), "rule__DeployConfigsLongSyntax__Group_1__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup_2(), "rule__DeployConfigsLongSyntax__Group_2__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup_3(), "rule__DeployConfigsLongSyntax__Group_3__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup_4(), "rule__DeployConfigsLongSyntax__Group_4__0");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGroup_5(), "rule__DeployConfigsLongSyntax__Group_5__0");
			builder.put(grammarAccess.getCredentialSpecAccess().getGroup_0(), "rule__CredentialSpec__Group_0__0");
			builder.put(grammarAccess.getCredentialSpecAccess().getGroup_0_1(), "rule__CredentialSpec__Group_0_1__0");
			builder.put(grammarAccess.getCredentialSpecAccess().getGroup_1(), "rule__CredentialSpec__Group_1__0");
			builder.put(grammarAccess.getDeployAccess().getGroup(), "rule__Deploy__Group__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_0(), "rule__Deploy__Group_2_0__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_1(), "rule__Deploy__Group_2_1__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_2(), "rule__Deploy__Group_2_2__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_3(), "rule__Deploy__Group_2_3__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_4(), "rule__Deploy__Group_2_4__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_5(), "rule__Deploy__Group_2_5__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_6(), "rule__Deploy__Group_2_6__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_7(), "rule__Deploy__Group_2_7__0");
			builder.put(grammarAccess.getDeployAccess().getGroup_2_8(), "rule__Deploy__Group_2_8__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup(), "rule__Placement__Group__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup_2_0(), "rule__Placement__Group_2_0__0");
			builder.put(grammarAccess.getPlacementAccess().getGroup_2_1(), "rule__Placement__Group_2_1__0");
			builder.put(grammarAccess.getRestartPolicyAccess().getGroup(), "rule__RestartPolicy__Group__0");
			builder.put(grammarAccess.getRestartPolicyAccess().getGroup_2_0(), "rule__RestartPolicy__Group_2_0__0");
			builder.put(grammarAccess.getRestartPolicyAccess().getGroup_2_1(), "rule__RestartPolicy__Group_2_1__0");
			builder.put(grammarAccess.getRestartPolicyAccess().getGroup_2_2(), "rule__RestartPolicy__Group_2_2__0");
			builder.put(grammarAccess.getRestartPolicyAccess().getGroup_2_3(), "rule__RestartPolicy__Group_2_3__0");
			builder.put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_0(), "rule__Config__Group_2_0__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_1(), "rule__Config__Group_2_1__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_2(), "rule__Config__Group_2_2__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_3(), "rule__Config__Group_2_3__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_4(), "rule__Config__Group_2_4__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2_5(), "rule__Config__Group_2_5__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup(), "rule__Healthcheck__Group__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0(), "rule__Healthcheck__Group_2_0__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_1(), "rule__Healthcheck__Group_2_1__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_2(), "rule__Healthcheck__Group_2_2__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_3(), "rule__Healthcheck__Group_2_3__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_4(), "rule__Healthcheck__Group_2_4__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_5(), "rule__Healthcheck__Group_2_5__0");
			builder.put(grammarAccess.getLoggingAccess().getGroup(), "rule__Logging__Group__0");
			builder.put(grammarAccess.getLoggingAccess().getGroup_2(), "rule__Logging__Group_2__0");
			builder.put(grammarAccess.getLoggingAccess().getGroup_2_0(), "rule__Logging__Group_2_0__0");
			builder.put(grammarAccess.getLoggingAccess().getGroup_2_1(), "rule__Logging__Group_2_1__0");
			builder.put(grammarAccess.getPortsAccess().getGroup_0(), "rule__Ports__Group_0__0");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getGroup(), "rule__PortLongSyntax__Group__0");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getGroup_1(), "rule__PortLongSyntax__Group_1__0");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getGroup_2(), "rule__PortLongSyntax__Group_2__0");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getGroup_3(), "rule__PortLongSyntax__Group_3__0");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getGroup_4(), "rule__PortLongSyntax__Group_4__0");
			builder.put(grammarAccess.getServiceSecretsAccess().getGroup_0(), "rule__ServiceSecrets__Group_0__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup(), "rule__ServiceSecretsLongSyntax__Group__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup_1(), "rule__ServiceSecretsLongSyntax__Group_1__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup_2(), "rule__ServiceSecretsLongSyntax__Group_2__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup_3(), "rule__ServiceSecretsLongSyntax__Group_3__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup_4(), "rule__ServiceSecretsLongSyntax__Group_4__0");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGroup_5(), "rule__ServiceSecretsLongSyntax__Group_5__0");
			builder.put(grammarAccess.getUlimitsAccess().getGroup_0(), "rule__Ulimits__Group_0__0");
			builder.put(grammarAccess.getUlimitsAccess().getGroup_1(), "rule__Ulimits__Group_1__0");
			builder.put(grammarAccess.getServiceVolumesAccess().getGroup(), "rule__ServiceVolumes__Group__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup(), "rule__ServiceVolumeLongSyntax__Group__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_3(), "rule__ServiceVolumeLongSyntax__Group_3__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_4(), "rule__ServiceVolumeLongSyntax__Group_4__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_5(), "rule__ServiceVolumeLongSyntax__Group_5__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_6(), "rule__ServiceVolumeLongSyntax__Group_6__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_7(), "rule__ServiceVolumeLongSyntax__Group_7__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_7_2(), "rule__ServiceVolumeLongSyntax__Group_7_2__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_8(), "rule__ServiceVolumeLongSyntax__Group_8__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_8_2(), "rule__ServiceVolumeLongSyntax__Group_8_2__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_9(), "rule__ServiceVolumeLongSyntax__Group_9__0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getGroup_9_2(), "rule__ServiceVolumeLongSyntax__Group_9_2__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup(), "rule__Volumes__Group__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup_4_0(), "rule__Volumes__Group_4_0__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup_4_1(), "rule__Volumes__Group_4_1__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup_4_2(), "rule__Volumes__Group_4_2__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup_4_3(), "rule__Volumes__Group_4_3__0");
			builder.put(grammarAccess.getVolumesAccess().getGroup_4_4(), "rule__Volumes__Group_4_4__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup(), "rule__Networks__Group__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_0(), "rule__Networks__Group_4_0__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_1(), "rule__Networks__Group_4_1__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_2(), "rule__Networks__Group_4_2__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_3(), "rule__Networks__Group_4_3__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_4(), "rule__Networks__Group_4_4__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_5(), "rule__Networks__Group_4_5__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_6(), "rule__Networks__Group_4_6__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_7(), "rule__Networks__Group_4_7__0");
			builder.put(grammarAccess.getNetworksAccess().getGroup_4_8(), "rule__Networks__Group_4_8__0");
			builder.put(grammarAccess.getIpamAccess().getGroup(), "rule__Ipam__Group__0");
			builder.put(grammarAccess.getIpamAccess().getGroup_2(), "rule__Ipam__Group_2__0");
			builder.put(grammarAccess.getIpamAccess().getGroup_3(), "rule__Ipam__Group_3__0");
			builder.put(grammarAccess.getConfigsAccess().getGroup(), "rule__Configs__Group__0");
			builder.put(grammarAccess.getConfigsAccess().getGroup_4_0(), "rule__Configs__Group_4_0__0");
			builder.put(grammarAccess.getConfigsAccess().getGroup_4_1(), "rule__Configs__Group_4_1__0");
			builder.put(grammarAccess.getConfigsAccess().getGroup_4_2(), "rule__Configs__Group_4_2__0");
			builder.put(grammarAccess.getSecretsAccess().getGroup(), "rule__Secrets__Group__0");
			builder.put(grammarAccess.getSecretsAccess().getGroup_4_0(), "rule__Secrets__Group_4_0__0");
			builder.put(grammarAccess.getSecretsAccess().getGroup_4_1(), "rule__Secrets__Group_4_1__0");
			builder.put(grammarAccess.getSecretsAccess().getGroup_4_2(), "rule__Secrets__Group_4_2__0");
			builder.put(grammarAccess.getValueOrListAccess().getGroup_0(), "rule__ValueOrList__Group_0__0");
			builder.put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
			builder.put(grammarAccess.getListAccess().getGroup_1(), "rule__List__Group_1__0");
			builder.put(grammarAccess.getMappingAccess().getGroup(), "rule__Mapping__Group__0");
			builder.put(grammarAccess.getMappingWithPrefixAndColonAccess().getGroup(), "rule__MappingWithPrefixAndColon__Group__0");
			builder.put(grammarAccess.getMappingWithoutPrefixAndColonAccess().getGroup(), "rule__MappingWithoutPrefixAndColon__Group__0");
			builder.put(grammarAccess.getMappingWithPrefixAndEqualAccess().getGroup(), "rule__MappingWithPrefixAndEqual__Group__0");
			builder.put(grammarAccess.getMappingWithoutPrefixAndEqualAccess().getGroup(), "rule__MappingWithoutPrefixAndEqual__Group__0");
			builder.put(grammarAccess.getDockerComposeAccess().getVersionAssignment_3(), "rule__DockerCompose__VersionAssignment_3");
			builder.put(grammarAccess.getDockerComposeAccess().getServicesAssignment_4_3(), "rule__DockerCompose__ServicesAssignment_4_3");
			builder.put(grammarAccess.getDockerComposeAccess().getVolumesAssignment_5_3(), "rule__DockerCompose__VolumesAssignment_5_3");
			builder.put(grammarAccess.getDockerComposeAccess().getNetworksAssignment_6_3(), "rule__DockerCompose__NetworksAssignment_6_3");
			builder.put(grammarAccess.getDockerComposeAccess().getConfigsAssignment_7_3(), "rule__DockerCompose__ConfigsAssignment_7_3");
			builder.put(grammarAccess.getDockerComposeAccess().getSecretsAssignment_8_3(), "rule__DockerCompose__SecretsAssignment_8_3");
			builder.put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
			builder.put(grammarAccess.getServiceAccess().getBuildAssignment_4_0_2(), "rule__Service__BuildAssignment_4_0_2");
			builder.put(grammarAccess.getServiceAccess().getCap_addAssignment_4_1_2(), "rule__Service__Cap_addAssignment_4_1_2");
			builder.put(grammarAccess.getServiceAccess().getCap_dropAssignment_4_2_2(), "rule__Service__Cap_dropAssignment_4_2_2");
			builder.put(grammarAccess.getServiceAccess().getCgroup_parentAssignment_4_3_2(), "rule__Service__Cgroup_parentAssignment_4_3_2");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_4_4_2(), "rule__Service__CommandAssignment_4_4_2");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_4_5_2(), "rule__Service__CommandAssignment_4_5_2");
			builder.put(grammarAccess.getServiceAccess().getContainer_nameAssignment_4_6_2(), "rule__Service__Container_nameAssignment_4_6_2");
			builder.put(grammarAccess.getServiceAccess().getCredential_specAssignment_4_7_2(), "rule__Service__Credential_specAssignment_4_7_2");
			builder.put(grammarAccess.getServiceAccess().getDepends_onAssignment_4_8_2(), "rule__Service__Depends_onAssignment_4_8_2");
			builder.put(grammarAccess.getServiceAccess().getDeployAssignment_4_9_2(), "rule__Service__DeployAssignment_4_9_2");
			builder.put(grammarAccess.getServiceAccess().getDevicesAssignment_4_10_2(), "rule__Service__DevicesAssignment_4_10_2");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_4_11_2(), "rule__Service__DnsAssignment_4_11_2");
			builder.put(grammarAccess.getServiceAccess().getDnsAssignment_4_12_2(), "rule__Service__DnsAssignment_4_12_2");
			builder.put(grammarAccess.getServiceAccess().getDomainnameAssignment_4_13_2(), "rule__Service__DomainnameAssignment_4_13_2");
			builder.put(grammarAccess.getServiceAccess().getEntrypointAssignment_4_14_2(), "rule__Service__EntrypointAssignment_4_14_2");
			builder.put(grammarAccess.getServiceAccess().getEnv_fileAssignment_4_15_2(), "rule__Service__Env_fileAssignment_4_15_2");
			builder.put(grammarAccess.getServiceAccess().getEnvironmentAssignment_4_16_2(), "rule__Service__EnvironmentAssignment_4_16_2");
			builder.put(grammarAccess.getServiceAccess().getExposeAssignment_4_17_2(), "rule__Service__ExposeAssignment_4_17_2");
			builder.put(grammarAccess.getServiceAccess().getExternal_linksAssignment_4_18_2(), "rule__Service__External_linksAssignment_4_18_2");
			builder.put(grammarAccess.getServiceAccess().getExternal_linksAssignment_4_19_2(), "rule__Service__External_linksAssignment_4_19_2");
			builder.put(grammarAccess.getServiceAccess().getHealthcheckAssignment_4_20_2(), "rule__Service__HealthcheckAssignment_4_20_2");
			builder.put(grammarAccess.getServiceAccess().getHostnameAssignment_4_21_2(), "rule__Service__HostnameAssignment_4_21_2");
			builder.put(grammarAccess.getServiceAccess().getImageAssignment_4_22_1(), "rule__Service__ImageAssignment_4_22_1");
			builder.put(grammarAccess.getServiceAccess().getInitAssignment_4_23_2(), "rule__Service__InitAssignment_4_23_2");
			builder.put(grammarAccess.getServiceAccess().getIpcAssignment_4_24_2(), "rule__Service__IpcAssignment_4_24_2");
			builder.put(grammarAccess.getServiceAccess().getIsolationAssignment_4_25_2(), "rule__Service__IsolationAssignment_4_25_2");
			builder.put(grammarAccess.getServiceAccess().getLabelsAssignment_4_26_2(), "rule__Service__LabelsAssignment_4_26_2");
			builder.put(grammarAccess.getServiceAccess().getLinksAssignment_4_27_2(), "rule__Service__LinksAssignment_4_27_2");
			builder.put(grammarAccess.getServiceAccess().getLoggingAssignment_4_28_2(), "rule__Service__LoggingAssignment_4_28_2");
			builder.put(grammarAccess.getServiceAccess().getMac_addressAssignment_4_29_2(), "rule__Service__Mac_addressAssignment_4_29_2");
			builder.put(grammarAccess.getServiceAccess().getNetwork_modeAssignment_4_30_2(), "rule__Service__Network_modeAssignment_4_30_2");
			builder.put(grammarAccess.getServiceAccess().getNetworksAssignment_4_31_2(), "rule__Service__NetworksAssignment_4_31_2");
			builder.put(grammarAccess.getServiceAccess().getPidAssignment_4_32_2(), "rule__Service__PidAssignment_4_32_2");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_4_33_2(), "rule__Service__PortsAssignment_4_33_2");
			builder.put(grammarAccess.getServiceAccess().getPrivilegedAssignment_4_34_2(), "rule__Service__PrivilegedAssignment_4_34_2");
			builder.put(grammarAccess.getServiceAccess().getRead_onlyAssignment_4_35_2(), "rule__Service__Read_onlyAssignment_4_35_2");
			builder.put(grammarAccess.getServiceAccess().getRestartAssignment_4_36_2(), "rule__Service__RestartAssignment_4_36_2");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_4_37_2(), "rule__Service__SecretsAssignment_4_37_2");
			builder.put(grammarAccess.getServiceAccess().getSecurity_optAssignment_4_38_2(), "rule__Service__Security_optAssignment_4_38_2");
			builder.put(grammarAccess.getServiceAccess().getShm_sizeAssignment_4_39_2(), "rule__Service__Shm_sizeAssignment_4_39_2");
			builder.put(grammarAccess.getServiceAccess().getStdin_openAssignment_4_40_2(), "rule__Service__Stdin_openAssignment_4_40_2");
			builder.put(grammarAccess.getServiceAccess().getStop_grace_periodAssignment_4_41_2(), "rule__Service__Stop_grace_periodAssignment_4_41_2");
			builder.put(grammarAccess.getServiceAccess().getStop_signalAssignment_4_42_2(), "rule__Service__Stop_signalAssignment_4_42_2");
			builder.put(grammarAccess.getServiceAccess().getSysctlsAssignment_4_43_2(), "rule__Service__SysctlsAssignment_4_43_2");
			builder.put(grammarAccess.getServiceAccess().getSysctlsAssignment_4_44_2(), "rule__Service__SysctlsAssignment_4_44_2");
			builder.put(grammarAccess.getServiceAccess().getTtyAssignment_4_45_2(), "rule__Service__TtyAssignment_4_45_2");
			builder.put(grammarAccess.getServiceAccess().getUlimitsAssignment_4_46_2(), "rule__Service__UlimitsAssignment_4_46_2");
			builder.put(grammarAccess.getServiceAccess().getUserAssignment_4_47_2(), "rule__Service__UserAssignment_4_47_2");
			builder.put(grammarAccess.getServiceAccess().getUserns_modeAssignment_4_48_2(), "rule__Service__Userns_modeAssignment_4_48_2");
			builder.put(grammarAccess.getServiceAccess().getVolumesAssignment_4_49_2(), "rule__Service__VolumesAssignment_4_49_2");
			builder.put(grammarAccess.getServiceAccess().getWorking_dirAssignment_4_50_2(), "rule__Service__Working_dirAssignment_4_50_2");
			builder.put(grammarAccess.getBuildAccess().getBuildAssignment_0_1(), "rule__Build__BuildAssignment_0_1");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getContextAssignment_1_0_2(), "rule__BuildLongSyntax__ContextAssignment_1_0_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getDockerfileAssignment_1_1_2(), "rule__BuildLongSyntax__DockerfileAssignment_1_1_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getArgsAssignment_1_2_2(), "rule__BuildLongSyntax__ArgsAssignment_1_2_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getLabelsAssignment_1_3_2(), "rule__BuildLongSyntax__LabelsAssignment_1_3_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getCache_fromAssignment_1_4_2(), "rule__BuildLongSyntax__Cache_fromAssignment_1_4_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getNetworkAssignment_1_5_2(), "rule__BuildLongSyntax__NetworkAssignment_1_5_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getTargetAssignment_1_6_2(), "rule__BuildLongSyntax__TargetAssignment_1_6_2");
			builder.put(grammarAccess.getBuildLongSyntaxAccess().getShm_sizeAssignment_1_7_2(), "rule__BuildLongSyntax__Shm_sizeAssignment_1_7_2");
			builder.put(grammarAccess.getDeployConfigsAccess().getListAssignment_0_1(), "rule__DeployConfigs__ListAssignment_0_1");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getSourceAssignment_1_3(), "rule__DeployConfigsLongSyntax__SourceAssignment_1_3");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getTargetAssignment_2_2(), "rule__DeployConfigsLongSyntax__TargetAssignment_2_2");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getUidAssignment_3_2(), "rule__DeployConfigsLongSyntax__UidAssignment_3_2");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getGidAssignment_4_2(), "rule__DeployConfigsLongSyntax__GidAssignment_4_2");
			builder.put(grammarAccess.getDeployConfigsLongSyntaxAccess().getModeAssignment_5_2(), "rule__DeployConfigsLongSyntax__ModeAssignment_5_2");
			builder.put(grammarAccess.getCredentialSpecAccess().getFileAssignment_0_1_2(), "rule__CredentialSpec__FileAssignment_0_1_2");
			builder.put(grammarAccess.getCredentialSpecAccess().getRegistryAssignment_1_2(), "rule__CredentialSpec__RegistryAssignment_1_2");
			builder.put(grammarAccess.getDeployAccess().getEndpoint_modeAssignment_2_0_2(), "rule__Deploy__Endpoint_modeAssignment_2_0_2");
			builder.put(grammarAccess.getDeployAccess().getLabelsAssignment_2_1_2(), "rule__Deploy__LabelsAssignment_2_1_2");
			builder.put(grammarAccess.getDeployAccess().getModeAssignment_2_2_2(), "rule__Deploy__ModeAssignment_2_2_2");
			builder.put(grammarAccess.getDeployAccess().getPlacementAssignment_2_3_2(), "rule__Deploy__PlacementAssignment_2_3_2");
			builder.put(grammarAccess.getDeployAccess().getReplicasAssignment_2_4_2(), "rule__Deploy__ReplicasAssignment_2_4_2");
			builder.put(grammarAccess.getDeployAccess().getResourcesAssignment_2_5_2(), "rule__Deploy__ResourcesAssignment_2_5_2");
			builder.put(grammarAccess.getDeployAccess().getRestart_policyAssignment_2_6_2(), "rule__Deploy__Restart_policyAssignment_2_6_2");
			builder.put(grammarAccess.getDeployAccess().getRollback_configAssignment_2_7_2(), "rule__Deploy__Rollback_configAssignment_2_7_2");
			builder.put(grammarAccess.getDeployAccess().getUpdate_configAssignment_2_8_2(), "rule__Deploy__Update_configAssignment_2_8_2");
			builder.put(grammarAccess.getPlacementAccess().getConstraintsAssignment_2_0_2(), "rule__Placement__ConstraintsAssignment_2_0_2");
			builder.put(grammarAccess.getPlacementAccess().getPreferencesAssignment_2_1_2(), "rule__Placement__PreferencesAssignment_2_1_2");
			builder.put(grammarAccess.getRestartPolicyAccess().getConditionAssignment_2_0_2(), "rule__RestartPolicy__ConditionAssignment_2_0_2");
			builder.put(grammarAccess.getRestartPolicyAccess().getDelayAssignment_2_1_2(), "rule__RestartPolicy__DelayAssignment_2_1_2");
			builder.put(grammarAccess.getRestartPolicyAccess().getMax_attemptsAssignment_2_2_2(), "rule__RestartPolicy__Max_attemptsAssignment_2_2_2");
			builder.put(grammarAccess.getRestartPolicyAccess().getWindowAssignment_2_3_2(), "rule__RestartPolicy__WindowAssignment_2_3_2");
			builder.put(grammarAccess.getConfigAccess().getParallelismAssignment_2_0_2(), "rule__Config__ParallelismAssignment_2_0_2");
			builder.put(grammarAccess.getConfigAccess().getDelayAssignment_2_1_2(), "rule__Config__DelayAssignment_2_1_2");
			builder.put(grammarAccess.getConfigAccess().getFailure_actionAssignment_2_2_2(), "rule__Config__Failure_actionAssignment_2_2_2");
			builder.put(grammarAccess.getConfigAccess().getMonitorAssignment_2_3_2(), "rule__Config__MonitorAssignment_2_3_2");
			builder.put(grammarAccess.getConfigAccess().getMax_failure_ratioAssignment_2_4_2(), "rule__Config__Max_failure_ratioAssignment_2_4_2");
			builder.put(grammarAccess.getConfigAccess().getOrderAssignment_2_5_2(), "rule__Config__OrderAssignment_2_5_2");
			builder.put(grammarAccess.getHealthcheckAccess().getDisableAssignment_2_0_2(), "rule__Healthcheck__DisableAssignment_2_0_2");
			builder.put(grammarAccess.getHealthcheckAccess().getIntervalAssignment_2_1_2(), "rule__Healthcheck__IntervalAssignment_2_1_2");
			builder.put(grammarAccess.getHealthcheckAccess().getRetriesAssignment_2_2_2(), "rule__Healthcheck__RetriesAssignment_2_2_2");
			builder.put(grammarAccess.getHealthcheckAccess().getTestAssignment_2_3_2(), "rule__Healthcheck__TestAssignment_2_3_2");
			builder.put(grammarAccess.getHealthcheckAccess().getTimeoutAssignment_2_4_2(), "rule__Healthcheck__TimeoutAssignment_2_4_2");
			builder.put(grammarAccess.getHealthcheckAccess().getStart_periodAssignment_2_5_2(), "rule__Healthcheck__Start_periodAssignment_2_5_2");
			builder.put(grammarAccess.getLoggingAccess().getDriverAssignment_2_0_2(), "rule__Logging__DriverAssignment_2_0_2");
			builder.put(grammarAccess.getLoggingAccess().getOptionsAssignment_2_1_2(), "rule__Logging__OptionsAssignment_2_1_2");
			builder.put(grammarAccess.getPortsAccess().getPortsAssignment_0_1(), "rule__Ports__PortsAssignment_0_1");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getTargetAssignment_1_3(), "rule__PortLongSyntax__TargetAssignment_1_3");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getPublishedAssignment_2_2(), "rule__PortLongSyntax__PublishedAssignment_2_2");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getProtocolAssignment_3_2(), "rule__PortLongSyntax__ProtocolAssignment_3_2");
			builder.put(grammarAccess.getPortLongSyntaxAccess().getModeAssignment_4_2(), "rule__PortLongSyntax__ModeAssignment_4_2");
			builder.put(grammarAccess.getServiceSecretsAccess().getSecretAssignment_0_1(), "rule__ServiceSecrets__SecretAssignment_0_1");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getSourceAssignment_1_3(), "rule__ServiceSecretsLongSyntax__SourceAssignment_1_3");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getTargetAssignment_2_2(), "rule__ServiceSecretsLongSyntax__TargetAssignment_2_2");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getUidAssignment_3_2(), "rule__ServiceSecretsLongSyntax__UidAssignment_3_2");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getGidAssignment_4_2(), "rule__ServiceSecretsLongSyntax__GidAssignment_4_2");
			builder.put(grammarAccess.getServiceSecretsLongSyntaxAccess().getModeAssignment_5_2(), "rule__ServiceSecretsLongSyntax__ModeAssignment_5_2");
			builder.put(grammarAccess.getUlimitsAccess().getNameAssignment_0_0(), "rule__Ulimits__NameAssignment_0_0");
			builder.put(grammarAccess.getUlimitsAccess().getValueAssignment_0_2(), "rule__Ulimits__ValueAssignment_0_2");
			builder.put(grammarAccess.getUlimitsAccess().getNameAssignment_1_0(), "rule__Ulimits__NameAssignment_1_0");
			builder.put(grammarAccess.getUlimitsAccess().getSoftAssignment_1_5(), "rule__Ulimits__SoftAssignment_1_5");
			builder.put(grammarAccess.getUlimitsAccess().getHardAssignment_1_8(), "rule__Ulimits__HardAssignment_1_8");
			builder.put(grammarAccess.getServiceVolumesAccess().getVolumesAssignment_2_0(), "rule__ServiceVolumes__VolumesAssignment_2_0");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getTypeAssignment_2(), "rule__ServiceVolumeLongSyntax__TypeAssignment_2");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getSourceAssignment_3_2(), "rule__ServiceVolumeLongSyntax__SourceAssignment_3_2");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getTargetAssignment_4_2(), "rule__ServiceVolumeLongSyntax__TargetAssignment_4_2");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getRead_onlyAssignment_5_2(), "rule__ServiceVolumeLongSyntax__Read_onlyAssignment_5_2");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getConsistencyAssignment_6_2(), "rule__ServiceVolumeLongSyntax__ConsistencyAssignment_6_2");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getBindPropagationAssignment_7_2_3(), "rule__ServiceVolumeLongSyntax__BindPropagationAssignment_7_2_3");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getVolumeNocopyAssignment_8_2_3(), "rule__ServiceVolumeLongSyntax__VolumeNocopyAssignment_8_2_3");
			builder.put(grammarAccess.getServiceVolumeLongSyntaxAccess().getTmpfsSizeAssignment_9_2_3(), "rule__ServiceVolumeLongSyntax__TmpfsSizeAssignment_9_2_3");
			builder.put(grammarAccess.getVolumesAccess().getNameAssignment_1(), "rule__Volumes__NameAssignment_1");
			builder.put(grammarAccess.getVolumesAccess().getDriverAssignment_4_0_2(), "rule__Volumes__DriverAssignment_4_0_2");
			builder.put(grammarAccess.getVolumesAccess().getDriver_optsAssignment_4_1_2(), "rule__Volumes__Driver_optsAssignment_4_1_2");
			builder.put(grammarAccess.getVolumesAccess().getExternalAssignment_4_2_2(), "rule__Volumes__ExternalAssignment_4_2_2");
			builder.put(grammarAccess.getVolumesAccess().getLabelsAssignment_4_3_2(), "rule__Volumes__LabelsAssignment_4_3_2");
			builder.put(grammarAccess.getVolumesAccess().getCustomNameAssignment_4_4_2(), "rule__Volumes__CustomNameAssignment_4_4_2");
			builder.put(grammarAccess.getNetworksAccess().getNameAssignment_1(), "rule__Networks__NameAssignment_1");
			builder.put(grammarAccess.getNetworksAccess().getDriverAssignment_4_0_2(), "rule__Networks__DriverAssignment_4_0_2");
			builder.put(grammarAccess.getNetworksAccess().getDriver_optsAssignment_4_1_2(), "rule__Networks__Driver_optsAssignment_4_1_2");
			builder.put(grammarAccess.getNetworksAccess().getAttachableAssignment_4_2_2(), "rule__Networks__AttachableAssignment_4_2_2");
			builder.put(grammarAccess.getNetworksAccess().getEnable_ipv6Assignment_4_3_2(), "rule__Networks__Enable_ipv6Assignment_4_3_2");
			builder.put(grammarAccess.getNetworksAccess().getIpamAssignment_4_4_2(), "rule__Networks__IpamAssignment_4_4_2");
			builder.put(grammarAccess.getNetworksAccess().getInternalAssignment_4_5_2(), "rule__Networks__InternalAssignment_4_5_2");
			builder.put(grammarAccess.getNetworksAccess().getLabelsAssignment_4_6_2(), "rule__Networks__LabelsAssignment_4_6_2");
			builder.put(grammarAccess.getNetworksAccess().getExternalAssignment_4_7_2(), "rule__Networks__ExternalAssignment_4_7_2");
			builder.put(grammarAccess.getNetworksAccess().getCustomNameAssignment_4_8_2(), "rule__Networks__CustomNameAssignment_4_8_2");
			builder.put(grammarAccess.getIpamAccess().getDriverAssignment_2_2(), "rule__Ipam__DriverAssignment_2_2");
			builder.put(grammarAccess.getIpamAccess().getConfigAssignment_3_2(), "rule__Ipam__ConfigAssignment_3_2");
			builder.put(grammarAccess.getConfigsAccess().getNameAssignment_1(), "rule__Configs__NameAssignment_1");
			builder.put(grammarAccess.getConfigsAccess().getFileAssignment_4_0_2(), "rule__Configs__FileAssignment_4_0_2");
			builder.put(grammarAccess.getConfigsAccess().getExternalAssignment_4_1_2(), "rule__Configs__ExternalAssignment_4_1_2");
			builder.put(grammarAccess.getConfigsAccess().getCustomNameAssignment_4_2_2(), "rule__Configs__CustomNameAssignment_4_2_2");
			builder.put(grammarAccess.getSecretsAccess().getNameAssignment_1(), "rule__Secrets__NameAssignment_1");
			builder.put(grammarAccess.getSecretsAccess().getFileAssignment_4_0_2(), "rule__Secrets__FileAssignment_4_0_2");
			builder.put(grammarAccess.getSecretsAccess().getExternalAssignment_4_1_2(), "rule__Secrets__ExternalAssignment_4_1_2");
			builder.put(grammarAccess.getSecretsAccess().getCustomNameAssignment_4_2_2(), "rule__Secrets__CustomNameAssignment_4_2_2");
			builder.put(grammarAccess.getValueOrListAccess().getListAssignment_0_1(), "rule__ValueOrList__ListAssignment_0_1");
			builder.put(grammarAccess.getListAccess().getListAssignment_1_1(), "rule__List__ListAssignment_1_1");
			builder.put(grammarAccess.getMappingAccess().getMapAssignment_1_0(), "rule__Mapping__MapAssignment_1_0");
			builder.put(grammarAccess.getMappingAccess().getMapAssignment_1_1(), "rule__Mapping__MapAssignment_1_1");
			builder.put(grammarAccess.getMappingAccess().getMapAssignment_1_2(), "rule__Mapping__MapAssignment_1_2");
			builder.put(grammarAccess.getMappingAccess().getMapAssignment_1_3(), "rule__Mapping__MapAssignment_1_3");
			builder.put(grammarAccess.getMappingWithPrefixAndColonAccess().getNameAssignment_1(), "rule__MappingWithPrefixAndColon__NameAssignment_1");
			builder.put(grammarAccess.getMappingWithPrefixAndColonAccess().getValueAssignment_3(), "rule__MappingWithPrefixAndColon__ValueAssignment_3");
			builder.put(grammarAccess.getMappingWithoutPrefixAndColonAccess().getNameAssignment_0(), "rule__MappingWithoutPrefixAndColon__NameAssignment_0");
			builder.put(grammarAccess.getMappingWithoutPrefixAndColonAccess().getValueAssignment_2(), "rule__MappingWithoutPrefixAndColon__ValueAssignment_2");
			builder.put(grammarAccess.getMappingWithPrefixAndEqualAccess().getNameAssignment_1(), "rule__MappingWithPrefixAndEqual__NameAssignment_1");
			builder.put(grammarAccess.getMappingWithPrefixAndEqualAccess().getValueAssignment_3(), "rule__MappingWithPrefixAndEqual__ValueAssignment_3");
			builder.put(grammarAccess.getMappingWithoutPrefixAndEqualAccess().getNameAssignment_0(), "rule__MappingWithoutPrefixAndEqual__NameAssignment_0");
			builder.put(grammarAccess.getMappingWithoutPrefixAndEqualAccess().getValueAssignment_2(), "rule__MappingWithoutPrefixAndEqual__ValueAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ComposeFileGrammarAccess grammarAccess;

	@Override
	protected InternalComposeFileParser createParser() {
		InternalComposeFileParser result = new InternalComposeFileParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new ComposeFileTokenSource(super.createLexer(stream));
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ComposeFileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ComposeFileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
