/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.dockerFile;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON ARRAY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.dockerFile.JSON_ARRAY#getHead <em>Head</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.dockerFile.JSON_ARRAY#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getJSON_ARRAY()
 * @model
 * @generated
 */
public interface JSON_ARRAY extends Cmd, AddDestination, Entrypoint, Volume
{
  /**
   * Returns the value of the '<em><b>Head</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head</em>' attribute.
   * @see #setHead(String)
   * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getJSON_ARRAY_Head()
   * @model
   * @generated
   */
  String getHead();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.dockerFile.JSON_ARRAY#getHead <em>Head</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Head</em>' attribute.
   * @see #getHead()
   * @generated
   */
  void setHead(String value);

  /**
   * Returns the value of the '<em><b>Tail</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tail</em>' attribute list.
   * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getJSON_ARRAY_Tail()
   * @model unique="false"
   * @generated
   */
  EList<String> getTail();

} // JSON_ARRAY
