/**
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.dockerFile;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run With No Shell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.palladiosimulator.somox.docker.dockerFile.RunWithNoShell#getExecutable <em>Executable</em>}</li>
 *   <li>{@link org.palladiosimulator.somox.docker.dockerFile.RunWithNoShell#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getRunWithNoShell()
 * @model
 * @generated
 */
public interface RunWithNoShell extends Run
{
  /**
   * Returns the value of the '<em><b>Executable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executable</em>' attribute.
   * @see #setExecutable(String)
   * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getRunWithNoShell_Executable()
   * @model
   * @generated
   */
  String getExecutable();

  /**
   * Sets the value of the '{@link org.palladiosimulator.somox.docker.dockerFile.RunWithNoShell#getExecutable <em>Executable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Executable</em>' attribute.
   * @see #getExecutable()
   * @generated
   */
  void setExecutable(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute list.
   * @see org.palladiosimulator.somox.docker.dockerFile.DockerFilePackage#getRunWithNoShell_Params()
   * @model unique="false"
   * @generated
   */
  EList<String> getParams();

} // RunWithNoShell
