/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractComposeFileValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.palladiosimulator.somox.docker.compose.composeFile.ComposeFilePackage.eINSTANCE);
		return result;
	}
}
