/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComposeFileRuntimeModule extends AbstractComposeFileRuntimeModule {
}
