/*
 * generated by Xtext 2.21.0
 */
package org.palladiosimulator.somox.docker.compose;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ComposeFileStandaloneSetup extends ComposeFileStandaloneSetupGenerated {

	public static void doSetup() {
		new ComposeFileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
